# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serCalculo.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10serCalculo.proto\x12\ncalculator\"T\n\x0e\x63\x61lculoRequest\x12\x0f\n\x07numero1\x18\x01 \x01(\x05\x12\x0f\n\x07numero2\x18\x02 \x01(\x05\x12\x0f\n\x07numero3\x18\x03 \x01(\x05\x12\x0f\n\x07numero4\x18\x04 \x01(\x05\"$\n\x0f\x63\x61lculoResponse\x12\x11\n\tresultado\x18\x01 \x01(\x05\x32O\n\x07\x63\x61lculo\x12\x44\n\x07\x43\x61lculo\x12\x1a.calculator.calculoRequest\x1a\x1b.calculator.calculoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serCalculo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CALCULOREQUEST']._serialized_start=32
  _globals['_CALCULOREQUEST']._serialized_end=116
  _globals['_CALCULORESPONSE']._serialized_start=118
  _globals['_CALCULORESPONSE']._serialized_end=154
  _globals['_CALCULO']._serialized_start=156
  _globals['_CALCULO']._serialized_end=235
# @@protoc_insertion_point(module_scope)
