# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serCalculo_pb2 as serCalculo__pb2


class calculoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calculo = channel.unary_unary(
                '/calculator.calculo/Calculo',
                request_serializer=serCalculo__pb2.calculoRequest.SerializeToString,
                response_deserializer=serCalculo__pb2.calculoResponse.FromString,
                )


class calculoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Calculo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_calculoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calculo': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculo,
                    request_deserializer=serCalculo__pb2.calculoRequest.FromString,
                    response_serializer=serCalculo__pb2.calculoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.calculo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class calculo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Calculo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.calculo/Calculo',
            serCalculo__pb2.calculoRequest.SerializeToString,
            serCalculo__pb2.calculoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
