# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serOPuno_pb2 as serOPuno__pb2


class SumaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sumar = channel.unary_unary(
                '/calculator.SumaService/Sumar',
                request_serializer=serOPuno__pb2.SumarRequest.SerializeToString,
                response_deserializer=serOPuno__pb2.SumaResponse.FromString,
                )


class SumaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sumar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SumaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sumar': grpc.unary_unary_rpc_method_handler(
                    servicer.Sumar,
                    request_deserializer=serOPuno__pb2.SumarRequest.FromString,
                    response_serializer=serOPuno__pb2.SumaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.SumaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SumaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sumar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.SumaService/Sumar',
            serOPuno__pb2.SumarRequest.SerializeToString,
            serOPuno__pb2.SumaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
