# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serOPdos_pb2 as serOPdos__pb2


class RestaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resta = channel.unary_unary(
                '/calculator.RestaService/Resta',
                request_serializer=serOPdos__pb2.RestaRequest.SerializeToString,
                response_deserializer=serOPdos__pb2.RestaResponse.FromString,
                )


class RestaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Resta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resta': grpc.unary_unary_rpc_method_handler(
                    servicer.Resta,
                    request_deserializer=serOPdos__pb2.RestaRequest.FromString,
                    response_serializer=serOPdos__pb2.RestaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.RestaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RestaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Resta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.RestaService/Resta',
            serOPdos__pb2.RestaRequest.SerializeToString,
            serOPdos__pb2.RestaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
