# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serOPdos.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eserOPdos.proto\x12\ncalculator\"0\n\x0cRestaRequest\x12\x0f\n\x07numero3\x18\x01 \x01(\x05\x12\x0f\n\x07numero4\x18\x02 \x01(\x05\"\"\n\rRestaResponse\x12\x11\n\tresultado\x18\x01 \x01(\x05\x32N\n\x0cRestaService\x12>\n\x05Resta\x12\x18.calculator.RestaRequest\x1a\x19.calculator.RestaResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serOPdos_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESTAREQUEST']._serialized_start=30
  _globals['_RESTAREQUEST']._serialized_end=78
  _globals['_RESTARESPONSE']._serialized_start=80
  _globals['_RESTARESPONSE']._serialized_end=114
  _globals['_RESTASERVICE']._serialized_start=116
  _globals['_RESTASERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
