# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serOPuno.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eserOPuno.proto\x12\ncalculator\"0\n\x0cSumarRequest\x12\x0f\n\x07numero1\x18\x01 \x01(\x05\x12\x0f\n\x07numero2\x18\x02 \x01(\x05\"!\n\x0cSumaResponse\x12\x11\n\tresultado\x18\x01 \x01(\x05\x32L\n\x0bSumaService\x12=\n\x05Sumar\x12\x18.calculator.SumarRequest\x1a\x18.calculator.SumaResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serOPuno_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUMARREQUEST']._serialized_start=30
  _globals['_SUMARREQUEST']._serialized_end=78
  _globals['_SUMARESPONSE']._serialized_start=80
  _globals['_SUMARESPONSE']._serialized_end=113
  _globals['_SUMASERVICE']._serialized_start=115
  _globals['_SUMASERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
